Importation des librairies

In [2]:
import pandas as pd 
import requests

Importation du jeu de donn√©es

In [15]:
df_trafic=pd.read_csv("xtrain.csv")
df_trafic.head(50)

,timestamp,temperature,wind_speed,wind_gust_speed,rain_level,traffic_state,average_flow
0,2019-11-25T00:00:00+00:00,8.7,11.0,24.0,0.0,Fluid,218.1
1,2019-11-25T01:00:00+00:00,8.8,9.0,20.0,0.0,Fluid,144.3
2,2019-11-25T02:00:00+00:00,8.9,8.0,18.0,0.0,Fluid,110.0
3,2019-11-25T03:00:00+00:00,8.8,7.0,18.0,0.0,Fluid,143.8
4,2019-11-25T04:00:00+00:00,8.8,10.0,23.0,0.0,Fluid,315.1
5,2019-11-25T05:00:00+00:00,8.8,10.0,21.0,0.0,Fluid,626.9
6,2019-11-25T06:00:00+00:00,8.8,11.0,27.0,0.0,Fluid,854.2
7,2019-11-25T07:00:00+00:00,8.8,12.0,25.0,0.0,Fluid,1011.7
8,2019-11-25T08:00:00+00:00,8.5,13.0,26.0,0.0,Fluid,994.2
9,2019-11-25T09:00:00+00:00,8.5,12.0,26.0,0.0,Fluid,935.9
10,2019-11-25T10:00:00+00:00,9.6,11.0,23.0,0.0,Fluid,939.3
11,2019-11-25T11:00:00+00:00,11.6,20.0,39.0,0.0,Fluid,959.8
12,2019-11-25T12:00:00+00:00,12.8,18.0,37.0,0.0,Fluid,956.2
13,2019-11-25T13:00:00+00:00,13.2,17.0,44.0,0.0,Fluid,999.5
14,2019-11-25T14:00:00+00:00,12.2,17.0,40.0,0.0,NaN,NaN
15,2019-11-25T15:00:00+00:00,11.0,14.0,36.0,0.0,Fluid,967.3
16,2019-11-25T16:00:00+00:00,10.6,12.0,30.0,0.2,Fluid,970.0
17,2019-11-25T17:00:00+00:00,10.5,10.0,28.0,0.0,Fluid,1015.4
18,2019-11-25T18:00:00+00:00,10.6,11.0,27.0,0.0,Fluid,1004.3
19,2019-11-25T19:00:00+00:00,10.7,11.0,24.0,0.0,Fluid,850.4
20,2019-11-25T20:00:00+00:00,10.9,9.0,23.0,0.0,Fluid,643.9
21,2019-11-25T21:00:00+00:00,11.1,8.0,20.0,0.0,Fluid,584.2
22,2019-11-25T22:00:00+00:00,11.2,7.0,24.0,0.0,Fluid,518.2
23,2019-11-25T23:00:00+00:00,11.4,9.0,18.0,0.0,Fluid,349.5
24,2019-11-26T00:00:00+00:00,11.3,8.0,19.0,0.0,Fluid,221.9
25,2019-11-26T01:00:00+00:00,11.4,11.0,24.0,0.0,Fluid,151.0
26,2019-11-26T02:00:00+00:00,11.3,10.0,22.0,0.0,Fluid,120.4
27,2019-11-26T03:00:00+00:00,10.9,13.0,29.0,0.0,Fluid,161.2
28,2019-11-26T04:00:00+00:00,10.9,11.0,26.0,0.0,Fluid,321.0
29,2019-11-26T05:00:00+00:00,10.8,12.0,25.0,0.0,Fluid,634.9
30,2019-11-26T06:00:00+00:00,10.7,10.0,23.0,0.0,Fluid,873.9
31,2019-11-26T07:00:00+00:00,10.8,9.0,27.0,0.0,Fluid,1020.7
32,2019-11-26T08:00:00+00:00,11.0,12.0,31.0,0.0,Fluid,987.6
33,2019-11-26T09:00:00+00:00,11.3,16.0,36.0,0.0,Fluid,903.3
34,2019-11-26T10:00:00+00:00,11.2,11.0,32.0,0.8,Fluid,966.4
35,2019-11-26T11:00:00+00:00,11.3,14.0,41.0,0.4,Fluid,987.0
36,2019-11-26T12:00:00+00:00,11.6,10.0,35.0,0.0,Fluid,978.7
37,2019-11-26T13:00:00+00:00,12.2,13.0,32.0,0.0,Fluid,989.0
38,2019-11-26T14:00:00+00:00,12.7,13.0,34.0,0.0,Fluid,1000.7
39,2019-11-26T15:00:00+00:00,12.9,12.0,35.0,0.0,Fluid,999.6
40,2019-11-26T16:00:00+00:00,12.7,11.0,30.0,0.0,Fluid,997.0
41,2019-11-26T17:00:00+00:00,12.3,11.0,27.0,0.0,Fluid,1032.9
42,2019-11-26T18:00:00+00:00,12.2,13.0,31.0,0.0,Fluid,1055.8
43,2019-11-26T19:00:00+00:00,12.0,12.0,33.0,0.0,Fluid,928.3
44,2019-11-26T20:00:00+00:00,12.0,16.0,37.0,0.4,Fluid,656.2
45,2019-11-26T21:00:00+00:00,11.7,14.0,39.0,3.0,Fluid,596.6
46,2019-11-26T22:00:00+00:00,11.4,11.0,29.0,3.7,Fluid,665.3
47,2019-11-26T23:00:00+00:00,11.2,10.0,26.0,0.0,Fluid,453.2
48,2019-11-27T00:00:00+00:00,10.9,13.0,27.0,1.8,Fluid,271.6
49,2019-11-27T01:00:00+00:00,11.1,17.0,44.0,2.2,Fluid,178.2

In [17]:
df_real_time=pd.read_csv("ytrain_NpxebDC.csv")
df_real_time.head(20)
df_real_time.dropna()

/tmp/ipykernel_22537/3304128809.py:1: DtypeWarning: Columns (1,3,5,11,20,49,52,54,55,56,64,70,71,94,95,101,102,114,129,131,132,133,138,139,152,157,163,174,180,184,193,196,201,207,208,219,220,228,241,245,250,256,258,264,265,269,270,271,272,273) have mixed types. Specify dtype option on import or set low_memory=False.
  df_real_time=pd.read_csv("ytrain_NpxebDC.csv")

,timestamp,S7-T1,S2-T1,S19-T1,S56-T3,S85-T3,S16-T3,S16-T1,S94-T3,S28-T1,...,S47-T2,S65-T2,S32-T2,S21-T2,S13-T2,S97-T2,S25-T1,S25-T2,S98-T2,S99-T2
7142,2020-02-07T22:30:00+00:00,Down,Available,Available,Available,Down,Available,Passive,Offline,Available,...,Down,Available,Offline,Offline,Offline,Passive,Offline,Offline,Available,Down
7143,2020-02-07T22:45:00+00:00,Down,Available,Available,Available,Down,Available,Passive,Offline,Available,...,Down,Available,Offline,Offline,Offline,Passive,Offline,Offline,Available,Down
7144,2020-02-07T23:00:00+00:00,Down,Available,Available,Available,Down,Available,Passive,Offline,Available,...,Down,Available,Offline,Offline,Offline,Passive,Offline,Offline,Available,Down
7145,2020-02-07T23:15:00+00:00,Down,Available,Available,Available,Down,Available,Passive,Offline,Available,...,Down,Available,Offline,Offline,Offline,Passive,Offline,Offline,Available,Down
7146,2020-02-07T23:30:00+00:00,Down,Available,Available,Available,Down,Available,Passive,Offline,Available,...,Down,Available,Offline,Offline,Offline,Passive,Offline,Offline,Available,Down
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30000,2020-10-22T07:15:00+00:00,Down,Available,Available,Charging,Down,Available,Available,Passive,Available,...,Down,Offline,Offline,Offline,Available,Available,Available,Available,Available,Available
30001,2020-10-22T07:30:00+00:00,Down,Available,Available,Available,Down,Available,Available,Passive,Available,...,Down,Offline,Offline,Offline,Available,Available,Available,Available,Available,Available
30002,2020-10-22T07:45:00+00:00,Down,Available,Available,Available,Down,Available,Available,Passive,Available,...,Down,Offline,Offline,Offline,Available,Available,Available,Available,Available,Available
30003,2020-10-22T08:00:00+00:00,Down,Available,Available,Available,Down,Passive,Available,Passive,Available,...,Down,Offline,Offline,Offline,Available,Available,Available,Available,Available,Available
30004,2020-10-22T08:15:00+00:00,Down,Available,Available,Available,Down,Passive,Available,Passive,Available,...,Down,Offline,Offline,Offline,Available,Available,Available,Available,Offline,Available

In [ ]:
df_static=pd.read_csv("info_static.csv")
df_static

,t_id,s_id,latitude,longitude,street,city,zipcode,model
0,S84-T1,S84,48.863766,2.411770,104 RUE LOUIS LUMIERE,Paris,75020,"E/F, Combo, T2, CHAdeMO, T3"
1,S84-T3,S84,48.863766,2.411770,104 RUE LOUIS LUMIERE,Paris,75020,"CHAdeMO, T2, T3, E/F, Combo"
2,S86-T1,S86,48.890610,2.354230,27 RUE ORDENER,Paris,75018,"CHAdeMO, Combo, T2, T3, E/F"
3,S86-T2,S86,48.890610,2.354230,27 RUE ORDENER,Paris,75018,E/F
4,S86-T3,S86,48.890610,2.354230,27 RUE ORDENER,Paris,75018,"T3, Combo, CHAdeMO, E/F, T2"
...,...,...,...,...,...,...,...,...
268,S41-T2,S41,48.869370,2.303269,55 RUE PIERRE CHARRON,Paris,75008,E/F
269,S7-T2,S7,48.853445,2.386880,206 Boulevard Voltaire,Paris,75011,E/F
270,S57-T2,S57,48.885689,2.297463,4 AV GOURGAUD,Paris,75017,E/F
271,S47-T2,S47,48.820007,2.365661,107 BOULEVARD MASSENA,Paris,75013,E/F
272,S42-T2,S42,48.875854,2.309542,2 RUE LOUIS MURAT,Paris,75008,E/F